from pathlib import Path
import json,html
R=Path(__file__).resolve().parents[1]
c=json.loads((R/'catalog.json').read_text(encoding='utf-8'))
items=[s for s in c['stickers'] if s.get('output') and (R/s['output']).exists()]
cards=''.join(f'<article data-collection="{s["collection"]}"><img src="{html.escape(s["output"])}" alt="{html.escape(s["caption"] or s["id"])}"><h2>{html.escape(s["caption"] or s["id"])}</h2><p>{s["number"]} · {"מוכן" if s["status"]=="complete" else "בבדיקה"}</p><a href="{html.escape(s["output"])}" download>הורדת WebP</a></article>' for s in items)
page='''<!doctype html><html lang="he" dir="rtl"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>קידו — סטיקרים מונפשים</title><style>*{box-sizing:border-box}body{margin:0;background:#faf6ed;color:#262d2b;font:18px Arial,sans-serif}header{max-width:1200px;margin:auto;padding:56px 24px 25px}h1{font-size:44px;margin:8px 0}header p{line-height:1.7;max-width:700px}button{background:#286655;color:white;border:0;border-radius:24px;padding:12px 24px;cursor:pointer;font:inherit}main{max-width:1200px;margin:auto;display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:18px;padding:24px}article{background:white;border:1px solid #ddd9ce;border-radius:24px;padding:16px;text-align:center}article img{width:100%;aspect-ratio:1;object-fit:contain;background:#ece9e2;border-radius:16px}h2{font-size:20px}article p{font-size:14px;color:#61726b}a{color:#216750}body.dark{background:#151c20;color:#f8f1e5}.dark article{background:#252e32;border-color:#344148}.dark article img{background:#252932}.dark a{color:#a5d9c0}footer{text-align:center;padding:36px;font-size:14px}</style><header><div>KIDO • MOTION STICKERS</div><h1>רגשות קטנים. תנועה גדולה.</h1><p>חבילת הבנים עם הכיפה — תנועה נפרדת לכל סיטואציה. קובצי WebP מונפשים ושקופים, עם הכיתוב העברי המקורי.</p><button onclick="document.body.classList.toggle('dark')">החלפת רקע בהיר / כהה</button><p>COUNT סטיקרים נוצרו. התווית על כל כרטיס מציינת אם הבדיקה הושלמה.</p></header><main>CARDS</main><footer>לייבוא ל־WhatsApp נדרשת אפליקציה שתומכת בסטיקרים מונפשים. כל המקורות והפריימים נשמרים בפרויקט.</footer></html>'''.replace('CARDS',cards).replace('COUNT',str(len(items)))
labels={'boy':'בנים','boy-kippah':'בנים עם כיפה','girl':'בנות','products-he':'מוצרים בעברית','products-en':'מוצרים באנגלית'}
options='<option value="">כל האוספים</option>'+''.join(f'<option value="{group}">{labels.get(group,group)}</option>' for group in dict.fromkeys(s['collection'] for s in items))
control='<label for="collection">בחירת אוסף: </label><select id="collection" style="font:inherit;padding:10px;border-radius:12px" onchange="document.querySelectorAll(\'article\').forEach(card=>card.hidden=!!this.value&&card.dataset.collection!==this.value)">'+options+'</select>'
page=page.replace('חבילת הבנים עם הכיפה —','הסטיקרים של קידו —').replace('</header>',control+'</header>')
(R/'preview.html').write_text(page,encoding='utf-8')
print('Gallery:',len(items))
